spring:
    datasource:
    url: jdbc:mysql:///demo?SSL=false
    username: Zzzxb
    password: Happy1006
    driver-class-name: org.gjt.mm.mysql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
